# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
#
# install: `mkdir -p ~/.config/alacritty && echo -e "import:\n  - ~/dotfiles/alacritty.yml" > ~/.config/alacritty/alacritty.yml`

background_opacity: 1.0

selection:
  save_to_clipboard: true

startup_mode: Maximized

alt_send_esc: true

key_bindings:
  - { key: A,        mods: Alt,     chars: "\x1ba"                       }
  - { key: B,        mods: Alt,     chars: "\x1bb"                       }
  - { key: C,        mods: Alt,     chars: "\x1bc"                       }
  - { key: D,        mods: Alt,     chars: "\x1bd"                       }
  - { key: E,        mods: Alt,     chars: "\x1be"                       }
  - { key: F,        mods: Alt,     chars: "\x1bf"                       }
  - { key: G,        mods: Alt,     chars: "\x1bg"                       }
  - { key: H,        mods: Alt,     chars: "\x1bh"                       }
  - { key: I,        mods: Alt,     chars: "\x1bi"                       }
  - { key: J,        mods: Alt,     chars: "\x1bj"                       }
  - { key: K,        mods: Alt,     chars: "\x1bk"                       }
  - { key: L,        mods: Alt,     chars: "\x1bl"                       }
  - { key: M,        mods: Alt,     chars: "\x1bm"                       }
  - { key: N,        mods: Alt,     chars: "\x1bn"                       }
  - { key: O,        mods: Alt,     chars: "\x1bo"                       }
  - { key: P,        mods: Alt,     chars: "\x1bp"                       }
  - { key: Q,        mods: Alt,     chars: "\x1bq"                       }
  - { key: R,        mods: Alt,     chars: "\x1br"                       }
  - { key: S,        mods: Alt,     chars: "\x1bs"                       }
  - { key: T,        mods: Alt,     chars: "\x1bt"                       }
  - { key: U,        mods: Alt,     chars: "\x1bu"                       }
  - { key: V,        mods: Alt,     chars: "\x1bv"                       }
  - { key: W,        mods: Alt,     chars: "\x1bw"                       }
  - { key: X,        mods: Alt,     chars: "\x1bx"                       }
  - { key: Y,        mods: Alt,     chars: "\x1by"                       }
  - { key: Z,        mods: Alt,     chars: "\x1bz"                       }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;5A"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;5B"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;5C"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;5D"                   }
  - { key: Key0,     mods: Alt,     chars: "\x1b0"                       }
  - { key: Key1,     mods: Alt,     chars: "\x1b1"                       }
  - { key: Key2,     mods: Alt,     chars: "\x1b2"                       }
  - { key: Key3,     mods: Alt,     chars: "\x1b3"                       }
  - { key: Key4,     mods: Alt,     chars: "\x1b4"                       }
  - { key: Key5,     mods: Alt,     chars: "\x1b5"                       }
  - { key: Key6,     mods: Alt,     chars: "\x1b6"                       }
  - { key: Key7,     mods: Alt,     chars: "\x1b7"                       }
  - { key: Key8,     mods: Alt,     chars: "\x1b8"                       }
  - { key: Key9,     mods: Alt,     chars: "\x1b9"                       }
