require 'rake/testtask'

desc "Run tests (Docker required)"
Rake::TestTask.new(:test) do |t|
  t.test_files = ENV['TEST'] ? [ENV['TEST']] : FileList['test/test_*.rb']
  t.verbose = true
end

desc "Build the shared Docker image (owned by vim-webdav)"
task :docker_build do
  if system("docker image inspect vim-webdav-test > /dev/null 2>&1")
    puts "Docker image already exists"
  else
    Dir.chdir(File.expand_path('../vim-webdav', __dir__)) do
      sh "docker build -t vim-webdav-test -f test/Dockerfile ."
    end
  end
end

task :test => :docker_build

task :default => :test
