# Supported values: ssh, https
git_protocol: https
editor:
prompt: enabled
pager:
aliases:
  # co: pr checkout
  wpr: pr list --web
  wf: '!gh browse $(git ls-files | fzf)'
http_unix_socket:
browser:
