# env_path

[env]

[tools]
# tool
usage = "latest"
neovim = 'latest'
fzf = 'latest'
ripgrep = 'latest'
delta = 'latest'
# zellij = 'latest'
# difftastic = 'latest'
zoxide = 'latest'
fd = 'latest'
bat = 'latest'
dust = 'latest'
# yq, jq, rg, fd??

# devops
terraform = '1.1.8'
nova = '3.6.4'
awscli = 'latest'
github-cli = 'latest'
kubectl = 'latest'
krew = 'latest'
helm = 'latest'
k9s = 'latest'
# telepresence = 'latest'
# pre-commit = 'latest'

# lang
# python = { version="3.12.0", virtualenv=".venv" }
# python.version="{{ exec(command='cat .python-version') | split(pat='-') | first }}"
# python.virtualenv="{{env.HOME}}/.cache/venv/{{ exec(command='cat .python-version') }}"

ruby = ['system', '3.3.0']
# bun = '1.0.20'
# java = 'openjdk-21'
python = "3.12.0"

yamllint = "1.33.0"
tflint = "0.50.2"

node = '22'
"npm:yaml-language-server" = "latest"
"npm:stimulus-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"

# go = "latest"
# "go:github.com/mr-karan/doggo/cmd/doggo" = "latest"
# "go:github.com/DarthSim/hivemind" = "latest"
# "go:github.com/DarthSim/overmind/v2" = "latest"

# rust = "latest"
# "cargo:dog" = "latest"

# pip install --user pipx
# pipx = "latest"
# "pipx:kaskade" = "latest"

[alias.ruby]
dotfiles = '3.3.0'

# [alias.yarn]
# my_custom_node = '20'

[plugins]
usage = "https://github.com/jdx/mise-usage.git"

[tasks."yarn:latest"]
description = 'set yarn version to latest'
run = "yarn set version latest"
