# env_path

[env]

[tools]
# tool
neovim = 'latest'
fzf = 'latest'
zellij = 'latest'
# yq, jq, rg, fd??

# devops
terraform = '1.1.8'
nova = '3.6.4'
awscli = 'latest'
github-cli = 'latest'
kubectl = 'latest'
helm = 'latest'
k9s = 'latest'
# telepresence = 'latest'
# pre-commit = 'latest'

# lang
# python = { version="3.12.0", virtualenv=".venv" }
# python.version="{{ exec(command='cat .python-version') | split(pat='-') | first }}"
# python.virtualenv="{{env.HOME}}/.cache/venv/{{ exec(command='cat .python-version') }}"

ruby = ['system', '3.3.0']
node = '20.10.0'
bun = '1.0.20'
java = 'openjdk-21'
python = "3.12.0"

yamllint = "1.33.0"
tflint = "0.50.2"

[plugins]

# [alias.yarn]
# my_custom_node = '20'

[tasks."yarn:latest"]
description = 'set yarn version to latest'
run = "yarn set version latest"

[settings]
python_venv_auto_create = true

