[env]

[tools]
usage = "latest"
neovim = "latest"
fzf = "latest"
ripgrep = "latest"
delta = "latest"
zoxide = "latest"
fd = "latest"
bat = "latest"
dust = "latest"
jq = "latest"
just = "latest"
# dasel = "latest"

ruby = ["system", "3.3.0"]

"ubi:DarthSim/overmind" = "latest"
"ubi:DarthSim/hivemind" = "latest"
"ubi:mr-karan/doggo" = "latest"

[plugins]
usage = "https://github.com/jdx/mise-usage.git"

[tasks."yarn:latest"]
description = "set yarn version to latest"
run = "yarn set version latest"

[tasks."setup:devops"]
description = "setup devops tools"
run = """
#!/usr/bin/env bash
mise use -C $HOME --yes \
    terraform \
    nova \
    kubectl \
    awscli \
    github-cli \
    krew \
    helm \
    k9s \
    cargo:kdash
"""

[tasks."setup:ruby"]
description = "setup ruby depdenencies"
run = """
#!/usr/bin/env bash
case ${OSTYPE}
in
    darwin*)
        brew install openssl readline zlib
        ;;
    *)
        sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev
        ;;
esac
"""

[tasks."lsp:web"]
description = "setup LSP web frontent"
run = """
mise use --yes \
  npm:@tailwindcss/language-server \
  npm:typescript-language-server
mise set DOTS_LSP_WEB=1
"""

[tasks."docker"]
description = "start mise docker"
run = "docker run -it jdxcode/mise"
